### ISSUE TITLE
Configurer le Code Scanning

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/domaine-nc-gh-action#1]
https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

**Comment by Dougniel** [comment]
@adriens, je. t'affecte le ticket car je n'ai pas d'accès en écriture sur le projet, réaffecté le moi une fois que ce sera bon stp

En fait je n'ai même pas le droit de t'assigner

**Comment by adriens** [comment]
La stratégie de sécurité des repos par défaut a été changée hier : tu peux retester stp

**Comment by Dougniel** [comment]
C'est bon pour la repo, par contre CodeQL ne supporte pas l'analyse des yaml des GitHubs actions : https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/
